module.exports = [
 {
    data: {
      title: "Human Practices - iGEM NCKU",
      url: "",
      img: "",
      description: "",
      css: "/wiki/css/T--NCKU_Tainan--Layout.css",
			cover: "/wiki/images/cover/T--NCKU_Tainan--HP.png",
			overview1: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpOverview1.jpg",
			overview2: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpOverview2.jpg",
    },
    layout:  "./view/Human_Practices/index.hbs",
    filename: "./docs/Human_Practices/index.html"
  },
  {
    data: {
      title: "Integrated Practice - iGEM NCKU",
      url: "",
      img: "",
      description: "",
      css: "/wiki/css/T--NCKU_Tainan--Layout.css",
			cover: "/wiki/images/cover/T--NCKU_Tainan--Integrated.png",
			videoEdu: "",
			hpVideo1: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpVideo1.mp4",
			hpVideo2: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpVideo2.mp4",
			hpVideo3: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpVideo3.mp4",
			hpVideo4: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpVideo4.mp4",
			hpVideo5: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpVideo5.mp4",
			hpVideo6: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpVideo6.mp4",
			conf1: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpConf1.jpg",
			conf2: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpConf2.jpg",
			conf3: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpConf3.jpg",
			conf4: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpConf4.jpg",
			conf5: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpConf5.jpg",
			interview: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpInterview.jpg",
			visiting1: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpVisiting1.jpg",
			visiting2: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpVisiting2.jpg",
			exp1: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpExp1.jpg",
			exp2: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpExp2.jpg",
			exp3: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpExp3.jpg",
			round1: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpRound1.jpg",
			round2: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpRound2.jpg",
			round3: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpRound3.jpg",
    },
    layout:  "./view/Human_Practices/integrated.hbs",
    filename: "./docs/Human_Practices/integrated.html"
  },
  {
    data: {
      title: "Engagement - iGEM NCKU",
      url: "",
      img: "",
      description: "",
      css: "/wiki/css/T--NCKU_Tainan--Layout.css",
			cover: "/wiki/images/cover/T--NCKU_Tainan--Engagement.png",
			img: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpEngagement.jpg",
			meetup1: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpMeetup1.jpg",
			meetup2: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpMeetup2.jpg",
			skype: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpSkype.jpg",
			media: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpMedia.png",
    },
    layout:  "./view/Human_Practices/engagement.hbs",
    filename: "./docs/Human_Practices/engagement.html"
  },
  {
    data: {
      title: "HP Gold - iGEM NCKU",
      url: "",
      img: "",
      description: "",
      css: "/wiki/css/T--NCKU_Tainan--Layout.css",
			cover: "/wiki/images/cover/T--NCKU_Tainan--Integrated.png",
			conf1: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpConf1.jpg",
			conf2: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpConf2.jpg",
			conf3: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpConf3.jpg",
			conf4: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpConf4.jpg",
			conf5: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpConf5.jpg",
			exp1: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpExp1.jpg",
			exp2: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpExp2.jpg",
			exp3: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpExp3.jpg",
			round1: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpRound1.jpg",
			round2: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpRound2.jpg",
			round3: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpRound3.jpg",
			videoEdu: "",
			interview: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpInterview.jpg",
			visiting1: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpVisiting1.jpg",
			visiting2: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpVisiting2.jpg",
    },
    layout:  "./view/Human_Practices/hpGold.hbs",
    filename: "./docs/Human_Practices/hpGold.html"
  },
  {
    data: {
      title: "HP Silver - iGEM NCKU",
      url: "",
      img: "",
      description: "",
      css: "/wiki/css/T--NCKU_Tainan--Layout.css",
			cover: "/wiki/images/cover/T--NCKU_Tainan--HP.png",
			img: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpEngagement.jpg",
			meetup1: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpMeetup1.jpg",
			meetup2: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpMeetup2.jpg",
			skype: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpSkype.jpg",
			media: "/wiki/images/HumanPractices/T--NCKU_Tainan--hpMedia.png",
    },
    layout:  "./view/Human_Practices/hpSilver.hbs",
    filename: "./docs/Human_Practices/hpSilver.html"
  },
 ];

